### ISSUE TITLE
Use 'prop-types' package instead of React.PropTypes

### ISSUE THREAD

**Issue by MichaelDeBoey** [FloValence/react-konami#12]
`React.PropTypes` has been extracted to it's own package since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

CC: @ FloValence

**Comment by FloValence** [comment]
Hello @MichaelDeBoey ,

Thank you for the contribution, I'll update the npm package ASAP

**Comment by MichaelDeBoey** [comment]
@FloValence Any news on the release to npm? 🙂

**Comment by FloValence** [comment]
@MichaelDeBoey Version 0.4.0 available !
