### ISSUE TITLE
prevent for pushing old build/*

### ISSUE THREAD

**Issue by guillaumearm** [FloValence/react-konami#7]
Hi, I think we should add `build` folder in .gitignore
and use `-f` flag in version script : 

```
"version": "npm run build && git add -Af build"
```

this will prevent for accidentally pushing old build/*

**Comment by FloValence** [comment]
Hello Guillaume,
Yes, it's a good idea! I'll do this quickly.
Thank you

**Comment by guillaumearm** [comment]
but warning, i think it's a bad idea to tag new version on another branch than master.

example :
take 2 branches features, A and B : 
- A bump to v1.3
- B bump to v1.3 too

so who is right ?

**Comment by FloValence** [comment]
Yes, I was thinking about it, I think I'll add a commit hook that will keep the build up to date.

**Comment by FloValence** [comment]
Husky has been added to the package and runs a precommit hook.
